# Generated by Django 5.1.3 on 2025-04-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardPuzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board", models.CharField(max_length=100)),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                ("info", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="GamePuzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board", models.CharField(max_length=100)),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                ("solution", models.TextField()),
                ("info", models.TextField()),
                ("to_move", models.CharField(default="white", max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="info",
            field=models.TextField(default="info", max_length=255),
        ),
        migrations.AddField(
            model_name="game",
            name="moves",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="to_move",
            field=models.CharField(default="white", max_length=5),
        ),
        migrations.AlterField(
            model_name="game",
            name="board",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="game",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date created"),
        ),
    ]
